swagger: "2.0"
info:
  description: "This the microservice that handles all the requests about the stories database"
  version: "1.0.0"
  title: "Stories Microservice"
schemes:
- "http"
paths:
  /stories:
    get:
      operationId: filter-stories
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "start"
        type: "string"
      - in: "query"
        name: "end"
        type: "string"
      - in: "query"
        name: "writer_id"
        type: "integer"
      - in: "query"
        name: "drafts"
        type: "boolean"
      responses:
        '200':
          description: "Stories correctly loaded"
          schema:
            $ref: "#/definitions/Stories"
        
  /writers-last-stories:
    get:
      operationId: writers-last-stories
      produces:
      - "application/json"
      responses:
        '200':
          description: "Stories correctly loaded"
          schema:
            $ref: "#/definitions/Stories"

  /following-stories/{user_id}:
    get:
      operationId: following-stories
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "user_id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Stories correctly loaded"
          schema:
            $ref: "#/definitions/Stories"
        '404':
          description: "Not Found!"

  /retrieve-set-themes:
    get:
      operationId: retrieve-set-themes
      produces:
      - "application/json"
      responses:
        '200':
          description: "Stories correctly loaded"
          schema:
            $ref: "#/definitions/RetrieveSetThemeResponse"
        '404':
          description: "Not Found!"          

  /story/{story_id}/{user_id}:
    get:
      operationId: get_story_by_id
      produces:
      - "application/json"
      parameters:
      - in : "path"
        name: "story_id"
        type: "integer"
        required: true
        description: Object containing story_id to retrieve
      - in : "path"
        name: "user_id"
        type: "integer"
        required: true
        description: ID of the user making the request
      responses:
        '200':
          description: "Story correctly loaded"
          schema:
            $ref: '#/definitions/Story'
        '401':
          description: "Not Authorized"
        '404':
          description: "Not Found!"
    delete:
      operationId: delete_story_by_id
      consumes: 
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in : "path"
        name: "story_id"
        type: "integer"
        required: true
        description: Object containing story_id to retrieve
      - in : "path"
        name: "user_id"
        type: "integer"
        required: true
        description: ID of the user making the request
      responses:
        '204':
          description: "Story correctly deleted"
        '401':
          description: "Not Authorized"
        '404':
          description: "Not found!"
   
  /random_story/{user_id}:
    get:
      operationId: get-random-story
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "user_id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Random story correctly loaded"
          schema:
            $ref: '#/definitions/Story'
        '404':
          description: "Not Found!"
              
  /dislike/{story_id}:
    post:
      operationId: dislike
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "story_id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Dislike added"
        '404':
          description: "Not Found!"
    delete:
      operationId: remove_dislike
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "story_id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Dislike removed"
        '404':
          description: "Not Found!"
      
  /like/{story_id}:
    post:
      operationId: like
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "story_id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Like added"
        '404':
          description: "Not Found!"
    delete:
      operationId: remove_like
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "story_id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Like removed"
        '404':
          description: "Not Found!"
      
  /new-draft:
    post:
      operationId: new-draft
      consumes: 
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in : "body"
        name: "body"
        required: true
        description: Object containing theme and dice number 
        schema:
          $ref: "#/definitions/Draft-definition"  
      responses:
        '200':
          description: Inizialized a new draft, return a story_id
          schema:
            $ref: "#/definitions/SingleStoryID"
        '400':
          description: Error
                     
  /write-story: 
    put:
      operationId: write-story
      consumes: 
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in : "body"
        name: "body"
        required: true
        description: Object containing story_id
        schema:
          $ref: "#/definitions/SimplifiedStory"
      responses: 
        '200':
          description: "Update the story by the given ID"
        '404':
          description: "Resource not found"
          
definitions:
  Story:
    type: "object"
    properties:
      story_id:
        type: "integer"
      title:
        type: "string"
      text:
        type: "string"
      rolls_outcome:
        type: "string"
      theme:
        type: "string"
      date:
        type: "string"
      likes:
        type: "integer"
      dislikes:
        type: "integer"
      published:
        type: "boolean"
      author_id:
        type: "integer"
      author_name:
        type: "string"
    required:
    - "story_id"
    - "title"
    - "text"
    - "rolls_outcome"
    - "theme"
    - "date"
    - "likes"
    - "dislikes"
    - "published"
    - "author_id"
    - "author_name"
    additionalProperties: false

  SimplifiedStory:
    type: "object"
    properties:
      story_id:
        type: "integer"
      title:
        type: "string"
      text:
        type: "string"
      published:
        type: "boolean"
      author_name:
        type: "string"
    required:
    - "story_id"
    - "title"
    - "text"
    - "published"
    - "author_name"
    additionalProperties: false

  Stories:
    type: "object"
    properties:
      stories:
       type: "array"
       items:
          $ref: "#/definitions/Story"
    required:
    - "stories"
    additionalProperties: false

  StoryArray:
    type: "array"
    items:
      $ref: '#/definitions/Story'
      
  SingleStoryID:
    type: "object"
    properties:
      story_id:
        type: "integer"
      
  Date:
    type: "object"
    properties:
      beginDate:
        type: "string"
      endDate:
        type: "string"
    required: 
    - "beginDate"
    - "endDate"
    additionalProperties: false
     
  StoryId:
    type: "object"
    properties:
      story_id: 
        type: "integer"
    required:
    - "story_id"
    additionalProperties: false
    
  RetrieveSetThemeResponse:
    type: "object"
    properties:
      themes:
        type: "array"
        items:
          type: "string"
      dice_number:
        type: "integer"
    required:
    - "themes"
    - "dice_number"
    additionalProperties: false
    
  DiceOutcome:
    type: "string"

  Draft-definition:
    type: "object"
    properties:
      user_id:
        type: "integer"
      theme:
        type: "string"
      dice_number: 
        type: "integer"
    required:
    - "user_id"
    - "theme"
    - "dice_number"
    additionalProperties: false  